/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Jokenpo;

import java.awt.CardLayout;
import java.util.Random;

/**
 *
 * @author Angelica
 */
public class Jokenpo2 extends javax.swing.JFrame {
    

    /**
     * Creates new form Jokenpo2
     */
    public Jokenpo2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panRaiz = new javax.swing.JPanel();
        panInicio = new javax.swing.JPanel();
        lblJogar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panJogo = new javax.swing.JPanel();
        lblPedra = new javax.swing.JLabel();
        lblTesoura = new javax.swing.JLabel();
        lblPapel = new javax.swing.JLabel();
        lblJogo = new javax.swing.JLabel();
        panResultado = new javax.swing.JPanel();
        lblNovamente = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblJogador = new javax.swing.JLabel();
        lblComputador = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panSair = new javax.swing.JPanel();
        lblVoltar = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panCreditos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JoKenPo");
        setMaximumSize(new java.awt.Dimension(473, 473));
        setMinimumSize(new java.awt.Dimension(473, 473));
        setResizable(false);

        panRaiz.setMaximumSize(new java.awt.Dimension(473, 473));
        panRaiz.setMinimumSize(new java.awt.Dimension(473, 473));
        panRaiz.setPreferredSize(new java.awt.Dimension(473, 473));
        panRaiz.setLayout(new java.awt.CardLayout());

        panInicio.setMaximumSize(new java.awt.Dimension(473, 473));
        panInicio.setMinimumSize(new java.awt.Dimension(473, 473));
        panInicio.setLayout(null);

        lblJogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJogarMouseClicked(evt);
            }
        });
        panInicio.add(lblJogar);
        lblJogar.setBounds(140, 330, 190, 80);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/inicio.JPG"))); // NOI18N
        panInicio.add(jLabel7);
        jLabel7.setBounds(0, 0, 473, 473);

        panRaiz.add(panInicio, "panInicio");

        panJogo.setLayout(null);

        lblPedra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPedraMouseClicked(evt);
            }
        });
        panJogo.add(lblPedra);
        lblPedra.setBounds(10, 260, 120, 160);

        lblTesoura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTesouraMouseClicked(evt);
            }
        });
        panJogo.add(lblTesoura);
        lblTesoura.setBounds(160, 130, 160, 150);

        lblPapel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPapelMouseClicked(evt);
            }
        });
        panJogo.add(lblPapel);
        lblPapel.setBounds(340, 260, 120, 160);

        lblJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/jogo.JPG"))); // NOI18N
        panJogo.add(lblJogo);
        lblJogo.setBounds(0, 0, 473, 473);

        panRaiz.add(panJogo, "panJogo");

        panResultado.setLayout(null);

        lblNovamente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNovamente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovamenteMouseClicked(evt);
            }
        });
        panResultado.add(lblNovamente);
        lblNovamente.setBounds(10, 330, 120, 80);

        lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
        });
        panResultado.add(lblSair);
        lblSair.setBounds(350, 330, 120, 70);
        panResultado.add(lblJogador);
        lblJogador.setBounds(50, 70, 110, 110);
        panResultado.add(lblComputador);
        lblComputador.setBounds(300, 70, 110, 110);
        panResultado.add(lblResultado);
        lblResultado.setBounds(130, 190, 200, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resultado.jpg"))); // NOI18N
        panResultado.add(jLabel2);
        jLabel2.setBounds(0, 0, 473, 473);

        panRaiz.add(panResultado, "panResultado");

        panSair.setLayout(null);

        lblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });
        panSair.add(lblVoltar);
        lblVoltar.setBounds(140, 370, 190, 70);

        lblCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditosMouseClicked(evt);
            }
        });
        panSair.add(lblCreditos);
        lblCreditos.setBounds(340, 410, 130, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela sair.jpg"))); // NOI18N
        panSair.add(jLabel4);
        jLabel4.setBounds(0, 0, 473, 473);

        panRaiz.add(panSair, "panSair");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/creditos.JPG"))); // NOI18N

        javax.swing.GroupLayout panCreditosLayout = new javax.swing.GroupLayout(panCreditos);
        panCreditos.setLayout(panCreditosLayout);
        panCreditosLayout.setHorizontalGroup(
            panCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6)
        );
        panCreditosLayout.setVerticalGroup(
            panCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6)
        );

        panRaiz.add(panCreditos, "panCreditos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    int computador;
    
    private int setComp(){
        computador = new Random().nextInt(3);
        
        switch (computador) {
            case 0:
                lblComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/pedra computador.JPG")));
                break;
            case 1:
                lblComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/papel computador.JPG")));
                break;
            case 2:
                lblComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/tesoura computador.JPG")));
                break;
            
        }        
                
        return computador;
    }
    private void lblJogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJogarMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panJogo");
    }//GEN-LAST:event_lblJogarMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panSair");
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblPedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedraMouseClicked
        // TODO add your handling code here:
        this.setComp();
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panResultado");
        lblJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/pedra jogador.JPG")));
        switch (computador) {
            case 0:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/empate.jpg")));
            break;
            case 1:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/pedraperde.JPG")));
            break;
            case 2:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/pedravence.JPG")));
            break;
            
        }
    }//GEN-LAST:event_lblPedraMouseClicked

    private void lblTesouraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTesouraMouseClicked
        // TODO add your handling code here:
        this.setComp();
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panResultado");
        lblJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/tesoura jogador.JPG")));
        switch (computador) {
            case 0:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/tesouraperde.JPG")));
            break;
            case 1:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/tesouravence.JPG")));
            break;
            case 2:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/empate.jpg")));
            break;
            
        }
    }//GEN-LAST:event_lblTesouraMouseClicked

    private void lblPapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPapelMouseClicked
        // TODO add your handling code here:
        this.setComp();
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panResultado");
        lblJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/papel jogador.JPG")));
        switch (computador) {
            case 0:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/papelvence.JPG")));
            break;
            case 1:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/empate.jpg")));
            break;
            case 2:
                lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultado/papelperde.JPG")));
            break;
            
        }
    }//GEN-LAST:event_lblPapelMouseClicked

    private void lblNovamenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovamenteMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panJogo");
    }//GEN-LAST:event_lblNovamenteMouseClicked

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panInicio");
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void lblCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditosMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panCreditos");
    }//GEN-LAST:event_lblCreditosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jokenpo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jokenpo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jokenpo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jokenpo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jokenpo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblComputador;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblJogador;
    private javax.swing.JLabel lblJogar;
    private javax.swing.JLabel lblJogo;
    private javax.swing.JLabel lblNovamente;
    private javax.swing.JLabel lblPapel;
    private javax.swing.JLabel lblPedra;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblTesoura;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JPanel panCreditos;
    private javax.swing.JPanel panInicio;
    private javax.swing.JPanel panJogo;
    private javax.swing.JPanel panRaiz;
    private javax.swing.JPanel panResultado;
    private javax.swing.JPanel panSair;
    // End of variables declaration//GEN-END:variables

    private Object newRandom() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
